// <auto-generated>
// ReSharper disable All

namespace CarrierEngine.Infrastructure.Data.Models;

// Carrier
public class Carrier
{
    public int Id { get; set; } // Id (Primary key)
    public int BanyanCarrierId { get; set; } // BanyanCarrierId
    public string CarrierKey { get; set; } // CarrierKey (length: 50)
    public string ConfigurationData { get; set; } // ConfigurationData

    // Reverse navigation

    /// <summary>
    /// Child CarrierTrackingCodeMaps where [CarrierTrackingCodeMap].[CarrierId] point to this entity (FK_CarrierTrackingCodeMap_Carrier)
    /// </summary>
    public virtual ICollection<CarrierTrackingCodeMap> CarrierTrackingCodeMaps { get; set; } // CarrierTrackingCodeMap.FK_CarrierTrackingCodeMap_Carrier

    public Carrier()
    {
        CarrierTrackingCodeMaps = new List<CarrierTrackingCodeMap>();
    }
}

// </auto-generated>