// <auto-generated>
// ReSharper disable All

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using CarrierEngine.Infrastructure.Data.Configuration;
using CarrierEngine.Infrastructure.Data.Models;
using Microsoft.EntityFrameworkCore;

namespace CarrierEngine.Infrastructure.Data;

public class CarrierEngineDbContext : DbContext
{
    public CarrierEngineDbContext()
    {
    }

    public CarrierEngineDbContext(DbContextOptions<CarrierEngineDbContext> options)
    : base(options)
    {
    }

    public DbSet<Carrier> Carriers { get; set; } // Carrier
    public DbSet<CarrierTrackingCodeMap> CarrierTrackingCodeMaps { get; set; } // CarrierTrackingCodeMap

    //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //{
    //    if (!optionsBuilder.IsConfigured)
    //    {
    //        optionsBuilder.UseSqlServer(@"Data Source=SHNHWK-INSPIRON\SQLEXPRESS;Initial Catalog=CarrierEngine;Integrated Security=True;MultipleActiveResultSets=True");
    //    }
    //}
     

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.ApplyConfiguration(new CarrierConfiguration());
        modelBuilder.ApplyConfiguration(new CarrierTrackingCodeMapConfiguration());
    }

}