// <auto-generated>
// ReSharper disable All
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using CarrierEngine.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CarrierEngine.Data.Configuration;

// Carrier
public class CarrierConfiguration : IEntityTypeConfiguration<Carrier>
{
    public void Configure(EntityTypeBuilder<Carrier> builder)
    {
        builder.ToTable("Carrier", "dbo");
        builder.HasKey(x => x.Id).HasName("PK_Carrier").IsClustered();

        builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
        builder.Property(x => x.BanyanCarrierId).HasColumnName(@"BanyanCarrierId").HasColumnType("int").IsRequired();
        builder.Property(x => x.CarrierKey).HasColumnName(@"CarrierKey").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);
        builder.Property(x => x.ConfigurationData).HasColumnName(@"ConfigurationData").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
    }
}

// </auto-generated>