// <auto-generated>
// ReSharper disable All
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using CarrierEngine.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CarrierEngine.Data.Configuration;

// CarrierTrackingCodeMap
public class CarrierTrackingCodeMapConfiguration : IEntityTypeConfiguration<CarrierTrackingCodeMap>
{
    public void Configure(EntityTypeBuilder<CarrierTrackingCodeMap> builder)
    {
        builder.ToTable("CarrierTrackingCodeMap", "dbo");
        builder.HasKey(x => x.Id).HasName("PK_CarrierTrackingCodeMap").IsClustered();

        builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
        builder.Property(x => x.CarrierId).HasColumnName(@"CarrierId").HasColumnType("int").IsRequired();
        builder.Property(x => x.CarrierValue).HasColumnName(@"CarrierValue").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);
        builder.Property(x => x.BanyanCode).HasColumnName(@"BanyanCode").HasColumnType("varchar(5)").IsRequired().IsUnicode(false).HasMaxLength(5);
        builder.Property(x => x.MatchingType).HasColumnName(@"MatchingType").HasColumnType("varchar(10)").IsRequired().IsUnicode(false).HasMaxLength(10);
        builder.Property(x => x.BanyanStatusMap).HasColumnName(@"BanyanStatusMap").HasColumnType("int");

        // Foreign keys
        builder.HasOne(a => a.Carrier).WithMany(b => b.CarrierTrackingCodeMaps).HasForeignKey(c => c.CarrierId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_CarrierTrackingCodeMap_Carrier");

    }
}

// </auto-generated>