// <auto-generated>
// ReSharper disable All
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace CarrierEngine.Data.Models;

// CarrierTrackingCodeMap
public class CarrierTrackingCodeMap
{
    public int Id { get; set; } // Id (Primary key)
    public int CarrierId { get; set; } // CarrierId
    public string CarrierValue { get; set; } // CarrierValue (length: 50)
    public string BanyanCode { get; set; } // BanyanCode (length: 5)
    public string MatchingType { get; set; } // MatchingType (length: 10)

    // Foreign keys

    /// <summary>
    /// Parent Carrier pointed by [CarrierTrackingCodeMap].([CarrierId]) (FK_CarrierTrackingCodeMap_Carrier)
    /// </summary>
    public virtual Carrier Carrier { get; set; } // FK_CarrierTrackingCodeMap_Carrier
}

// </auto-generated>
